[server]
address = "0.0.0.0"
port = 8080
read_timeout = 15
write_timeout = 15

[paths]
download_directory = "downloads"
web_directory = "downloads/web"

[rabbitmq]
uri = "amqp://guest:guest@localhost:5672/"
queue_name = "download_tasks"
